## NumPy

**`NumPy`** es una librería utilizada para el manejo de arreglos (arrays) y matrices multidimensionales, cuenta con múltiples funciones para trabajar con estos objetos. Una matriz en **`NumPy`** es una cuadricula de valores, todos del mismo tipo e indexados.

```python
import numpy as np
```

In [1]:
import numpy as np

In [2]:
lista = [1, 2, 3]

In [3]:
type(lista)

list

In [4]:
# Usando np.array() podemos castear una lista a un objeto numpy.ndarray
type(np.array(lista))

numpy.ndarray

In [5]:
np.array(lista)

array([1, 2, 3])

### Arreglos (arrays) de 1 dimensión (vector).

| Método           | Atributo   |
|------------------|------------|
|**`.argmin()`**   |**`.dtype`**|
|**`.argmax()`**   |**`.ndim`** |
|**`.cumsum()`**   |**`.size`** |
|**`.cumprod()`**  |**`.shape`**|
|**`.dot()`**      | **`.T`**   |
|**`.flatten()`**  |            |
|**`.max()`**      |            |
|**`.min()`**      |            |
|**`.mean()`**     |            |
|**`.reshape()`**  |            |
|**`.transpose()`**|            |
|**`.sum()`**      |            |
|**`.sort()`**     |            |
|**`.tolist()`**   |            |

In [6]:
vector = [-2, 4, 1, 3.5]

vector = np.array(vector)

vector

array([-2. ,  4. ,  1. ,  3.5])

In [7]:
# .argmin() y .argmax() retornan el indice del minimo y del maximo respectivamente
print(vector.argmin())
print(vector.argmax())

0
1


In [8]:
# .cumsum() y cumprod() retorna un np.array() con la suma acumulada y el producto acumulado respectivamente

print(vector.cumsum())
print(vector.cumprod())

[-2.   2.   3.   6.5]
[ -2.  -8.  -8. -28.]


In [9]:
vector.shape

(4,)

In [10]:
# .reshape() cambia la "forma" de la matriz

matriz_1 = vector.reshape(1, 4)

matriz_1

array([[-2. ,  4. ,  1. ,  3.5]])

In [11]:
matriz_1.shape

(1, 4)

In [26]:
vector

array([-2. ,  1. ,  3.5,  4. ])

In [19]:
matriz_1

array([[-2. ,  1. ,  3.5,  4. ]])

In [12]:
# .transpose() hace la transpuesta de la matriz, también se puede usar .T

print(matriz_1.transpose())

print("-"*20)

print(matriz_1.T)

[[-2. ]
 [ 4. ]
 [ 1. ]
 [ 3.5]]
--------------------
[[-2. ]
 [ 4. ]
 [ 1. ]
 [ 3.5]]


In [13]:
# .tolist() retorna el array en una lista

matriz_1.tolist()

[[-2.0, 4.0, 1.0, 3.5]]

In [14]:
list(matriz_1)

[array([-2. ,  4. ,  1. ,  3.5])]

In [15]:
vector

array([-2. ,  4. ,  1. ,  3.5])

In [16]:
matriz_1

array([[-2. ,  4. ,  1. ,  3.5]])

In [17]:
# .flatten() retorna un vector plano con los elementos de la matriz

matriz_1.flatten()

array([-2. ,  4. ,  1. ,  3.5])

In [18]:
# .sort() ordena la matriz de menor a mayor, lo hace in-place

print("Antes de .sort()", vector)

vector.sort()

print("Después de .sort()", vector)

Antes de .sort() [-2.   4.   1.   3.5]
Después de .sort() [-2.   1.   3.5  4. ]


In [28]:
vector

array([-2. ,  1. ,  3.5,  4. ])

In [29]:
# .ndim retorna el número de dimensiones

vector.ndim

1

In [32]:
matriz_1.ndim

2

In [33]:
# .size retorna el número de elementos

vector.size

4

In [34]:
# .shape retorna en una tupla las dimesiones de la matriz

matriz_1.shape

(1, 4)

In [35]:
# .dtype retorna el tipo de dato de los elementos de la matriz

vector.dtype

dtype('float64')

### Arreglos (arrays) de 2 dimensiones (matrices).

Comparte los métodos y atributos de los vectores por que son de la misma clase.

Existen varias funciones para inicializar matrices o arrays:

| Función                  | Descripción                                                                             |
|--------------------------|-----------------------------------------------------------------------------------------|
|**`np.empty((n, m))`**    | Inicializa una matriz **nxm** vacia.                                                    |
|**`np.zeros((n, m))`**    | Inicializa una matriz **nxm** de ceros.                                                 |
|**`np.ones((n, m))`**     | Inicializa una matriz **nxm** de unos.                                                  |
|**`np.eye(n)`**           | Inicializa la matriz identidad de orden **n**.                                          |
|**`np.identity(n)`**      | Inicializa la matriz identidad de orden **n**.                                          |
|**`np.full(shape, elem)`**| Inicializa una matriz con la forma de **`shape`** usando los elementos de **`elem`**.   |
|**`np.linspace(a, b, p)`**| Inicializa un array de **`p`** elementos entre **`a`** y **`b`**, todos **x-distantes**.|

In [64]:
matriz = np.array([[3, 2, 1, 10], 
                   [4, 5, 6, 20], 
                   [7, 8, 9, 15]])

matriz

array([[ 3,  2,  1, 10],
       [ 4,  5,  6, 20],
       [ 7,  8,  9, 15]])

In [65]:
print(matriz)

[[ 3  2  1 10]
 [ 4  5  6 20]
 [ 7  8  9 15]]


In [66]:
matriz.shape

(3, 4)

In [67]:
matriz.sort()

In [69]:
matriz.flatten()

array([ 1,  2,  3, 10,  4,  5,  6, 20,  7,  8,  9, 15])

In [70]:
matriz.reshape(6, 2)

array([[ 1,  2],
       [ 3, 10],
       [ 4,  5],
       [ 6, 20],
       [ 7,  8],
       [ 9, 15]])

In [71]:
# Aunque muestre numeros dentro de la matriz, np.empty() la inicializa vacia, estos números que se ven
# Estan en memoria y numpy los usa para mostrar la matriz

empty = np.empty(shape = (5, 5), dtype = "float")

print(empty)

[[ 4.65968232e-310  0.00000000e+000  6.92730372e-310  4.87154264e-168
   6.92730420e-310]
 [ 3.50886576e+160  6.92730422e-310 -8.74423162e-083  0.00000000e+000
   0.00000000e+000]
 [ 6.92730414e-310  7.51246669e+272  6.92730415e-310 -4.21398072e+235
   0.00000000e+000]
 [ 0.00000000e+000  6.92730375e-310 -5.28707854e-241  6.92730415e-310
  -2.04914383e-135]
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000  0.00000000e+000
   1.66006057e-321]]


In [72]:
# Inicializa una matriz de 1's.

ones = np.ones(shape = (5, 5), dtype = "int8")

print(ones)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [73]:
# Inicializa una matriz de 0's.

zeros = np.zeros(shape = (5, 5), dtype = "int8")

print(zeros)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [74]:
# Matriz identidad

np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [78]:
# np.full() crea una lista con forma "shape" y la llena con un iterable.

full = np.full(shape = (5, 5), fill_value = range(5))

print(full)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [79]:
# np.full() crea una lista con forma "shape" y la llena con un iterable.

full = np.full(shape = (5, 5), fill_value = 10)

print(full)

[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]


In [80]:
# np.linspace(a, b, p) crea un array de "p" elementos entre "a" y "b", todos x-distantes

linspace = np.linspace(1, 12, 16)

print(linspace)

[ 1.          1.73333333  2.46666667  3.2         3.93333333  4.66666667
  5.4         6.13333333  6.86666667  7.6         8.33333333  9.06666667
  9.8        10.53333333 11.26666667 12.        ]


### Slicing en NumPy

En Python para hacer slicing de una lista de listas debiamos escribir primero la "fila" y de segundo la "columna" asi:
```python
lista[a][b]
```

Usando un **`np.array()`** podemos usar la siguiente notación:
```python
array[a, b]
```

Incluso, podemos pasar un **slicing** dentro del **slicing** para filtrar aun más los datos:
```python
array[a1 : a2, b1 : b2]
```

También podemos hacer **indexing** dentro del **slicing**

```python
array[[a1, a3], [b2, b4]]
```

In [81]:
matriz = np.array([[1, 0, 0, 0, 0],
                   [0, 0, 2, 0, 0],
                   [1, 1, 0, 0, 1],
                   [2, 1, 1, 1, 0],
                   [1, 2, 1, 2, 2]])

print(matriz)

[[1 0 0 0 0]
 [0 0 2 0 0]
 [1 1 0 0 1]
 [2 1 1 1 0]
 [1 2 1 2 2]]


In [82]:
# Hacer

matriz[4][1]

2

In [83]:
# Es igual que hacer

matriz[4, 1]

2

In [84]:
# Slicing
matriz[1:4, 1:4]

array([[0, 2, 0],
       [1, 0, 0],
       [1, 1, 1]])

In [86]:
# Slicing + Indexing

matriz[[1, 3], [2, 4]]

array([2, 0])

### Operaciones con Arrays

In [87]:
A = np.array([[20, 40], [30, 50]])
B = np.array([[4, 5], [2, 3]])

print(A)
print("-"*20)
print(B)

[[20 40]
 [30 50]]
--------------------
[[4 5]
 [2 3]]


In [88]:
# Suma

A + B

array([[24, 45],
       [32, 53]])

In [89]:
# Resta
A - B

array([[16, 35],
       [28, 47]])

In [90]:
# Multiplicación por escalar

A * 5

array([[100, 200],
       [150, 250]])

In [91]:
# Multiplicación elemento a elemento (no es la forma matemática de multiplicar)

A * B

array([[ 80, 200],
       [ 60, 150]])

In [92]:
# División por escalar

A / 5

array([[ 4.,  8.],
       [ 6., 10.]])

In [93]:
# Producto de matrices (también conocido como producto de vectorial)

A.dot(B)

array([[160, 220],
       [220, 300]])

In [94]:
print(A)
print("-"*20)
print(B)

[[20 40]
 [30 50]]
--------------------
[[4 5]
 [2 3]]


#### Concatenar

In [115]:
A

array([[20, 40],
       [30, 50]])

In [116]:
B

array([[4, 5],
       [2, 3]])

In [117]:
# Concatenar verticalmente

np.concatenate((A, B), axis = 0)

array([[20, 40],
       [30, 50],
       [ 4,  5],
       [ 2,  3]])

In [118]:
# Concatenar horizontalmente

np.concatenate((A, B), axis = 1)

array([[20, 40,  4,  5],
       [30, 50,  2,  3]])

### Números aleatorios en NumPy

|Función                             |Descripción                                                                                                                                         |
|------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------|
|**`np.random.random(n)`**           | Genera un número aleatorio entre 0 y 1, si damos el parametro **`n`** genera una lista de **`n`** elementos aleatorios entre 0 y 1, solo genera vectores.                                                                                                                       |
|**`np.random.rand(shape)`**         | Genera un array de forma **shape** con números aleatorios entre 0 y 1.                                                                             |
|**`np.random.randn(shape)`**        | Genera un array de forma **shape** con números aleatorios entre -1 y 1.                                                                           |
|**`no.random.randint(a, b, size)`** | Genera un array de tamaño **size** con numeros enteros aleatorios entre **a** y **b**.                                                             |
|**`np.random.choice(obj, size, p)`**| Genera un array de tamaño **size** con los elementos de **obj**, se le pueden dar pesos a los elementos usando **p**, retorna elementos repetidos.|
|**`np.random.seed(n)`**             | Genera una semilla.                                                                                                                                 |
|**`np.random.RandomState(n)`**      | Genera una semilla.                                                                                                                                 |

In [131]:
np.random.random(size = (5, 5))

array([[0.14675589, 0.09233859, 0.18626021, 0.34556073, 0.39676747],
       [0.53881673, 0.41919451, 0.6852195 , 0.20445225, 0.87811744],
       [0.02738759, 0.67046751, 0.4173048 , 0.55868983, 0.14038694],
       [0.19810149, 0.80074457, 0.96826158, 0.31342418, 0.69232262],
       [0.87638915, 0.89460666, 0.08504421, 0.03905478, 0.16983042]])

In [132]:
print(np.random.random())

print("-"*30)

print(np.random.random(5))

0.8781425034294131
------------------------------
[0.09834683 0.42110763 0.95788953 0.53316528 0.69187711]


In [135]:
print(np.random.rand())

print("-"*30)

print(np.random.rand(2, 3))

0.13002857211827767
------------------------------
[[0.01936696 0.67883553 0.21162812]
 [0.26554666 0.49157316 0.05336255]]


In [138]:
print(np.random.randn())

print("-"*30)

print(np.random.randn(2, 3))

0.3001703199558275
------------------------------
[[-0.35224985 -1.1425182  -0.34934272]
 [-0.20889423  0.58662319  0.83898341]]


In [140]:
print(np.random.randint(0, 10))

print("-"*30)

print(np.random.randint(1, 10, size = (5, 5)))

4
------------------------------
[[7 1 7 6 2]
 [3 2 6 5 1]
 [8 9 6 8 1]
 [4 2 5 5 7]
 [9 9 3 8 6]]


In [142]:
print(np.random.choice(a    = ["a", "e", "i", "o", "u"],
                       size = 10,
                       p    = [0.6, 0.1, 0.1, 0.1, 0.1])) 

['a' 'u' 'a' 'a' 'o' 'a' 'o' 'a' 'o' 'i']


In [149]:
for i in range(5):
    np.random.seed(42)
    print(np.random.randn())

0.4967141530112327
0.4967141530112327
0.4967141530112327
0.4967141530112327
0.4967141530112327


In [150]:
for i in range(4):
    
    rs = np.random.RandomState(2)
    
    print(rs.rand())
    print(rs.randint(0, 10))
    
    print(np.random.randn()) # No usa rs
    
    print("-"*30)    

0.43599490214200376
8
-0.13826430117118466
------------------------------
0.43599490214200376
8
0.6476885381006925
------------------------------
0.43599490214200376
8
1.5230298564080254
------------------------------
0.43599490214200376
8
-0.23415337472333597
------------------------------


In [153]:
np.random.seed(0)

for i in range(4):
    
    print(np.random.rand())
    print(np.random.randint(0, 10))
    print(np.random.randn())
    print("-"*30)  

0.5488135039273248
5
0.11849646073740812
------------------------------
0.8472517387841254
3
0.11396779497090676
------------------------------
0.6458941130666561
4
-0.2913939760114335
------------------------------
0.2726562945801132
1
-0.13309028458966213
------------------------------


In [29]:
# Código para establecer el número de decimales (Cambiar {0:0.2f} para elegir el número de decimales)

np.set_printoptions(formatter = {"float" : lambda x: "{0:0.2f}".format(x)})

np.random.randn(6, 6)

array([[0.61, 0.92, 0.38, -1.10, 0.30, 1.33],
       [-0.69, -0.15, -0.44, 1.85, 0.67, 0.41],
       [-0.77, 0.54, -0.67, 0.03, -0.64, 0.68],
       [0.58, -0.21, 0.40, -1.09, -1.49, 0.44],
       [0.17, 0.64, 2.38, 0.94, -0.91, 1.12],
       [-1.32, -0.46, -0.07, 1.71, -0.74, -0.83]])

In [30]:
np.random.randn(6, 6)

array([[-0.10, -0.66, 1.13, -1.08, -1.15, -0.44],
       [-0.50, 1.93, 0.95, 0.09, -1.23, 0.84],
       [-1.00, -1.54, 1.19, 0.32, 0.92, 0.32],
       [0.86, -0.65, -1.03, 0.68, -0.80, -0.69],
       [-0.46, 0.02, -0.35, -1.37, -0.64, -2.22],
       [0.63, -1.60, -1.10, 0.05, -0.74, 1.54]])

In [31]:
np.empty((5, 5), dtype = "float64")

array([[0.62, 0.44, 0.48, 0.98, 0.98],
       [0.92, 0.05, 0.62, 0.37, 0.19],
       [0.63, 0.04, 0.96, 0.83, 0.96],
       [0.48, 0.58, 0.84, 0.35, 0.03],
       [0.89, 0.57, 0.10, 0.56, 0.64]])

In [ ]:
################################################################################################################################